name: build_apk
on: push
jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@4389e6cbc6cb8a4b18c628ff96ff90be0e926aa8
        with:
          channel: stable
      - name: Build apk
        run: |
          flutter pub get
          flutter format --set-exit-if-changed .
          flutter analyze
          flutter build apk --debug