name: build
on: push
jobs:
  build-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.10.1'
          channel: stable
      - name: Build web
        run: |
          flutter pub get
          flutter build web